# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - run: go version
    - name: Pre-Install
      run: go get github.com/Clever/csvlint/cmd/csvlint
    - name: Test
      run: ~/go/bin/csvlint contest-1-market-data.csv && ~/go/bin/csvlint contest-1-scoreboard-data.csv && ~/go/bin/csvlint contest-2-market-data.csv && ~/go/bin/csvlint contest-2-scoreboard-data.csv
